### PR TITLE
update validation

### PR DESCRIPTION
**Pull request by lisakawai**
Previous check is not enough because it does not work when some items are removed. 
I updated it so that it does work in case of some removals.

### CODE REVIEW

**Comment by itohdak** [comment]
I tested in my laptop, but it didn't work properly.
I think it is because although you check if the input id is in the list,
you didn't apply the index of it when you replace it. 
I mean
`var id = path[4]`
shown in the url below isn't correct.
https://github.com/UTokyo-SDP/git-ex-02-41/pull/8/commits/704e08fc8f1586c667894b35caf25978c4de7e29#diff-b6a68d61529250580f3e0a773a626b8eR164

I think this problem will occur when some data are deleted,
and I also wrote a similar code for DELETE function,
so I want to PR for the DELETE function to the add_func branch first.
Is that okay?

**Comment by lisakawai** [comment]
I don'n understand what you mean. Could you let me know the patterns that it doesn't work?
I think the check of if target id exists or not is enough because if it does, we can replace the data of id that is provided by 'path[4]', right?

**Comment by itohdak** [comment]
Imagine the list is like below
`items = [{'id': 1, 'data': '1st'}, {'id': 3, 'data': '3rd'}, {'id': 9, 'data': '9th'}]`
and you want to PUT 'hoge' to the item whose id is 9: `$ curl -i -v --data '{"data":"hoge"}' -X PUT http://127.0.0.1:3000/id/9`.
Then item whose id is 9 actually exists.
However when replacing the data, with `var id = path[4]`, value of the variable `id` is now 9.
You can't access items[id] (that is equal to items[9]). Segmentation fault will occur.

**Comment by lisakawai** [comment]
Ah yes, you are right.

**Comment by lisakawai** [comment]
PTAL.

**Pull request merged**
